export const OPEN_INGREDIENT_MODAL:'OPEN_INGREDIENT_MODAL' = 'OPEN_INGREDIENT_MODAL';
export const CLOSE_INGREDIENT_MODAL:'CLOSE_INGREDIENT_MODAL' = 'CLOSE_INGREDIENT_MODAL';

export const OPEN_ORDER_DETAILS_MODAL:'OPEN_ORDER_DETAILS_MODAL' = 'OPEN_ORDER_DETAILS_MODAL';
export const CLOSE_ORDER_DETAILS_MODAL:'CLOSE_ORDER_DETAILS_MODAL' = 'CLOSE_ORDER_DETAILS_MODAL';